### ISSUE TITLE
Blob Management support in Resource Manager Gem

### ISSUE THREAD

**Issue by shaffan-chaudhry-confiz** [Azure/azure-sdk-ruby#16]
Hi,

How can I get blob properties using this gem. Does this gem has support for blob management?

**Comment by vishrutshah** [comment]
Hi @shaffan-chaudhry-confiz,

This repository contains all the gems for the [Azure ARM Management ](https://azure.microsoft.com/en-us/documentation/articles/resource-manager-deployment-model/) Plane, for now. That means you can manage storage account using [azure_mgmt_storage](https://github.com/Azure/azure-sdk-ruby/tree/master/resource_management/azure_mgmt_storage) gem. 

If you want to manage Azure blobs, queues & tables, please use [azure-storage](https://github.com/Azure/azure-storage-ruby) gem. Below are the links with examples for reference: 

[Blobs](https://github.com/Azure/azure-storage-ruby#blobs)
[Tables](https://github.com/Azure/azure-storage-ruby#tables)
[Queues](https://github.com/Azure/azure-storage-ruby#queues)

Thanks,

**Comment by shaffan-chaudhry-confiz** [comment]
Thank you.
