### ISSUE TITLE
Site_Instance deserialization expects "kind" property to exist

### ISSUE THREAD

**Issue by vicp-iq** [Azure/azure-sdk-ruby#18]
The following line expects a kind property to exist on the site_instance object:

https://github.com/Azure/azure-sdk-ruby/blob/master/resource_management/azure_mgmt_web/lib/azure_mgmt_web/models/site_instance.rb#L80

It's not there, and it's not on the parent either:
https://github.com/Azure/autorest/blob/master/ClientRuntimes/Ruby/ms-rest-azure/lib/ms_rest_azure/resource.rb

**Comment by vicp-iq** [comment]
So, I opened this issue because of the error that occurred telling me about the kind property.  If that's been degraded from error to warning, that might be sufficient to close this.

**Comment by vishrutshah** [comment]
@vicp-iq Thanks a lot for opening an issue and follow up. Yes, we have downgraded that error into warning due with [azure_mgmt_web ](https://rubygems.org/gems/azure_mgmt_web/versions/0.4.0) v0.4.0. 

Thanks a lot for your time and feedback. We appreciate it.
