### ISSUE TITLE
Getting wrong tenantid from wrong issuer

### ISSUE THREAD

**Issue by kavitakanojiya** [Azure/azure-sdk-ruby#31]
I am not sure what wrong I am doing but I consistently get this error:
"response": {
    "body": "{\"error\":{\"code\":\"InvalidAuthenticationTokenTenant\",\"message\":\"The access token is from the wrong issuer 'https://sts.windows.net/9654e12a-f42f-40ba-b988-4381bfff9e9e/'. It must match the tenant 'https://sts.windows.net/a8c0964e-6c4f-4a30-bb6d-35ace2711b35/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/a8c0964e-6c4f-4a30-bb6d-35ace2711b35' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.\"}}",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "content-type": "application/json; charset=utf-8",
      "expires": "-1",
      "www-authenticate": "Bearer authorization_uri=\"https://login.windows.net/a8c0964e-6c4f-4a30-bb6d-35ace2711b35\", error=\"invalid_token\", error_description=\"The access token is from the wrong issuer. It must match the tenant associated with this subscription. Please use correct authority to get the token.\"",
      "x-ms-failure-cause": "gateway",
      "x-ms-request-id": "34c571e1-c387-4d73-817f-69031cbc3983",
      "x-ms-correlation-request-id": "34c571e1-c387-4d73-817f-69031cbc3983",
      "x-ms-routing-request-id": "SOUTHEASTASIA:20160723T143233Z:34c571e1-c387-4d73-817f-69031cbc3983",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "date": "Sat, 23 Jul 2016 14:32:33 GMT",
      "connection": "close",
      "content-length": "677"
    },
    "status": 401
  }

Please advise.

**Comment by vishrutshah** [comment]
@kavitakanojiya Thanks for reporting an issue. Could you please send us some reference code that you are writing and tell us the gems and version you are using? This'd help us narrow down the issues and enable us to help you better. Thanks!

**Comment by kavitakanojiya** [comment]
Thanks for your reply.

I have added only `gem 'azure_mgmt_compute', '~> 0.4.0'`

Here is the code I am running:
`client_id = 'some-client-id'
tenant_id = 'some-tenant-id'
secret = 'some-secret'
subscription_id = 'some-subscription-id'
token_provider = MsRestAzure::ApplicationTokenProvider.new(tenant_id, client_id, secret)
credentials = MsRest::TokenCredentials.new(token_provider)

include Azure::ARM::Compute
include Azure::ARM::Compute::Models

client = ComputeManagementClient.new(credentials)
client.subscription_id = subscription_id
windows_config = WindowsConfiguration.new
windows_config.provision_vmagent = true
windows_config.enable_automatic_updates = true

os_profile = OSProfile.new
os_profile.computer_name = 'testvm1'
os_profile.admin_username = 'testvm1'
os_profile.admin_password = 'P@ssword1'
os_profile.windows_configuration = windows_config
os_profile.secrets = []

hardware_profile = HardwareProfile.new
hardware_profile.vm_size = 'Standard_A0'
params = VirtualMachine.new
params.type = 'Microsoft.Compute/virtualMachines'

params.location = 'westus'
promise = client.virtual_machines.create_or_update_async('existing_resource_group_name', 'name_of_new_vm', params)`

Also, as per above version, VirtualMachineProperties is removed so I am not able to assign properties to VirtualMachine object.

LMK if this can help.

Thanks.

**Comment by vishrutshah** [comment]
@kavitakanojiya Your code looks correct but It looks like you are authenticated against the common tenant (9654e12a-f42f-40ba-b988-4381bfff9e9e), but now you are trying access data from a subscription which belongs to a separate tenant (a8c0964e-6c4f-4a30-bb6d-35ace2711b35) - and you don't have an AccessToken for this new tenant.

The similar case is explained @ http://www.bizbert.com/bizbert/2015/11/16/Listing+Subscriptions+And+Logic+Apps+From+NET.aspx Please double check and make sure that you are authorizing against the same tenant. Let us know if this helps. 

Thanks

**Comment by kavitakanojiya** [comment]
@vishrutshah , thanks. I will verify.

**Comment by kavitakanojiya** [comment]
And what about VirtualMachineProperties.new mentioned in readme for `azure_mgmt_compute` ? since in new version, this class no longer exists.

**Comment by vishrutshah** [comment]
@kavitakanojiya Thanks for pointing that out. This gems are evolving fast and README is out dated with respect to version 0.4.0. We'll fix it soon. 

But all the properties of old class VirtualMachineProperties should be now found in [VirtualMachine ](https://github.com/Azure/azure-sdk-ruby/blob/master/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/virtual_machine.rb#L11) class. Please refer [virtual_machines_spec](https://github.com/Azure/azure-sdk-ruby/blob/master/azure_mgmt_compute/spec/virtual_machines_spec.rb) for VM operations. 

Please let us know if you are having any issue. Thanks a lot for your feedback.

**Comment by veronicagg** [comment]
Readme is now fixed.
