### ISSUE TITLE
 `<main>': uninitialized constant Azure::ARM::Compute::Models::VirtualMachineProperties (NameError)

### ISSUE THREAD

**Issue by bjd145** [Azure/azure-sdk-ruby#37]
I'm trying to create a VM and following the documentation at - https://github.com/Azure/azure-sdk-ruby/tree/master/azure_mgmt_compute
but everytime that I run the basic script I get the following error:

manager@master:~$ /opt/puppetlabs/puppet/bin/ruby ./create_vm.rb
./create_vm.rb:20:in `<main>': uninitialized constant Azure::ARM::Compute::Models::VirtualMachineProperties (NameError)

My ruby script is as follows:
require 'azure_mgmt_compute'

include Azure::ARM::Compute
include Azure::ARM::Compute::Models

subscription_id = "2deb88fe-eca8-499a-adb9-___"
tenant_id       = "72f988bf-86f1-41af-91ab-___"
client_id       = "4e565daf-621d-48d3-b010-___"
secret          = "+LcBmmlUSDMYu7t6ylwj8c87___="

token_provider = MsRestAzure::ApplicationTokenProvider.new(tenant_id, client_id, secret)
credentials = MsRest::TokenCredentials.new(token_provider)

client = ComputeManagementClient.new(credentials)
client.subscription_id = subscription_id
props = Azure::ARM::Compute::Models::VirtualMachineProperties.new

-------------------------------------------------------------------------------
Ruby Version:
manager@master:~$ /opt/puppetlabs/puppet/bin/ruby --version
ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux]

My gems installed:
manager@master:~$ /opt/puppetlabs/puppet/bin/gem list

*** LOCAL GEMS ***

addressable (2.4.0)
azure (0.7.5)
azure-core (0.1.2)
azure-credentials (0.1.2)
azure_mgmt_compute (0.4.0)
azure_mgmt_network (0.4.0)
azure_mgmt_resources (0.4.0)
azure_mgmt_storage (0.4.0)

**Comment by vishrutshah** [comment]
Hi @bjd145, 

Thanks for reporting the issue. We are updating this sdks very frequently and I see that README has been outdated (VirtualMachineProperties model has been removed in v0.4.0) . I've a PR out for the corrected version of README PR #36. For time being could you please reference the test [create virtual machine and vm extension](https://github.com/Azure/azure-sdk-ruby/blob/master/azure_mgmt_compute/spec/virtual_machines_spec.rb#L30) that demonstrates how to create a VM. 

We apologize for your inconvenience. Please let us know in case you are still having an trouble.

**Comment by bjd145** [comment]
Thanks @vishrutshah .  That would probably explain the issues I'm having with Puppet's Azure module. I'll review the reference and update my code.

**Comment by veronicagg** [comment]
Readme is now updated.
